# Generated by Django 4.1.6 on 2023-08-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
