# Generated by Django 4.1.6 on 2023-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_mail_user_remove_review_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='Цена'),
        ),
    ]
